# Generated by Django 4.1.7 on 2023-04-15 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("current", models.FloatField(blank=True, null=True)),
                ("available", models.FloatField(blank=True, null=True)),
                (
                    "iso_currency_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("limit", models.FloatField(blank=True, null=True)),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("subtype", models.CharField(blank=True, max_length=100, null=True)),
                ("mask", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "verification_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("class_type", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "official_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("institution_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accountId", models.CharField(blank=True, max_length=100, null=True)),
                ("account_owner", models.IntegerField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("authorized_date", models.DateField(blank=True, null=True)),
                ("authorized_datetime", models.DateTimeField(blank=True, null=True)),
                ("category", models.JSONField(blank=True, null=True)),
                (
                    "category_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("check_number", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField(blank=True, max_length=100, null=True)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "iso_currency_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("location", models.JSONField(blank=True, null=True)),
                (
                    "merchant_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_channel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_meta", models.JSONField(blank=True, null=True)),
                ("pending", models.BooleanField(blank=True, null=True)),
                (
                    "pending_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "personal_finance_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "unofficial_currency_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boltxplaid.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "transfer_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "public_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("wallet", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "link_session_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institution",
                        to="boltxplaid.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalAccount",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("account_id", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("current", models.FloatField(blank=True, null=True)),
                ("available", models.FloatField(blank=True, null=True)),
                (
                    "iso_currency_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("limit", models.FloatField(blank=True, null=True)),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("subtype", models.CharField(blank=True, max_length=100, null=True)),
                ("mask", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "verification_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("class_type", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "official_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="boltxplaid.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical account",
                "verbose_name_plural": "historical accounts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("frequency", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="boltxplaid.item",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
