# Generated by Django 4.1.7 on 2023-04-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="cursor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalaccount",
            name="cursor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cursor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
