# Generated by Django 4.1.7 on 2023-04-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0002_account_cursor_historicalaccount_cursor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="cursor",
        ),
        migrations.RemoveField(
            model_name="historicalaccount",
            name="cursor",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="cursor",
        ),
    ]
