# Generated by Django 4.1.7 on 2023-04-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0003_remove_account_cursor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="latest_cursor",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
