# Generated by Django 4.1.7 on 2023-04-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0005_requestedtokens"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequestedTokens",
        ),
    ]
