# Generated by Django 4.1.7 on 2023-04-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0008_alter_plaiditem_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plaiditem",
            name="institution_id",
        ),
        migrations.RemoveField(
            model_name="plaiditem",
            name="institution_name",
        ),
        migrations.AddField(
            model_name="plaiditem",
            name="institution",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plaiditem",
            name="transfer_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plaiditem",
            name="wallet",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
