# Generated by Django 4.1.7 on 2023-04-16 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boltxplaid", "0010_plaiditem_update_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaidAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("current", models.FloatField(blank=True, null=True)),
                ("available", models.FloatField(blank=True, null=True)),
                (
                    "iso_currency_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("limit", models.FloatField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("subtype", models.CharField(blank=True, max_length=100, null=True)),
                ("mask", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "verification_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("class_type", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "official_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boltxplaid.plaiditem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPlaidAccount",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("account_id", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("current", models.FloatField(blank=True, null=True)),
                ("available", models.FloatField(blank=True, null=True)),
                (
                    "iso_currency_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("limit", models.FloatField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("subtype", models.CharField(blank=True, max_length=100, null=True)),
                ("mask", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "verification_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("class_type", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "official_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="boltxplaid.plaiditem",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical plaid account",
                "verbose_name_plural": "historical plaid accounts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
