# Generated by Django 4.1.7 on 2023-04-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0011_plaidaccount_historicalplaidaccount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plaiditem",
            name="institution",
        ),
        migrations.AddField(
            model_name="plaiditem",
            name="institution_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plaiditem",
            name="institution_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
