# Generated by Django 4.1.7 on 2023-04-16 02:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0013_historicalplaidaccount_unofficial_currency_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaidTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(blank=True, max_length=100, null=True)),
                ("account_owner", models.IntegerField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("authorized_date", models.DateField(blank=True, null=True)),
                ("authorized_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "category_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("check_number", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField(blank=True, max_length=100, null=True)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "iso_currency_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("location", models.JSONField(blank=True, null=True)),
                (
                    "merchant_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_channel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_meta", models.JSONField(blank=True, null=True)),
                ("pending", models.BooleanField(blank=True, null=True)),
                (
                    "pending_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "personal_finance_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "unofficial_currency_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "latest_cursor",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "plaid_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boltxplaid.plaidaccount",
                    ),
                ),
            ],
        ),
    ]
