# Generated by Django 4.1.7 on 2023-04-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0015_plaiditem_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalaccount",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalaccount",
            name="item",
        ),
        migrations.RemoveField(
            model_name="historicalaccount",
            name="user",
        ),
        migrations.RemoveField(
            model_name="item",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="item",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="account",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="HistoricalAccount",
        ),
        migrations.DeleteModel(
            name="Institution",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
