# Generated by Django 4.1.7 on 2023-04-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0016_remove_historicalaccount_history_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaidRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("token", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
