# Generated by Django 4.1.7 on 2023-04-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0019_apr_credit_mortgage_propertyaddress_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditLiability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_overdue", models.BooleanField(default=False)),
                (
                    "last_payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("last_payment_date", models.DateField()),
                (
                    "last_statement_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("last_statement_issue_date", models.DateField()),
                (
                    "minimum_payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("next_payment_due_date", models.DateField()),
                (
                    "plaid_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boltxplaid.plaidaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MortgageLiability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=100)),
                (
                    "current_late_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "escrow_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("has_pmi", models.BooleanField()),
                ("has_prepayment_penalty", models.BooleanField()),
                (
                    "interest_rate_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("interest_rate_type", models.CharField(max_length=50)),
                (
                    "last_payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("last_payment_date", models.DateField()),
                ("loan_term", models.CharField(max_length=50)),
                ("loan_type_description", models.CharField(max_length=50)),
                ("maturity_date", models.DateField()),
                (
                    "next_monthly_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("next_payment_due_date", models.DateField()),
                ("origination_date", models.DateField()),
                (
                    "origination_principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "past_due_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "plaid_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boltxplaid.plaidaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentLiability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=100)),
                ("disbursement_dates", models.DateField()),
                ("expected_payoff_date", models.DateField()),
                ("guarantor", models.CharField(max_length=50)),
                (
                    "interest_rate_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_overdue", models.BooleanField(default=False)),
                (
                    "last_payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("last_payment_date", models.DateField()),
                (
                    "last_statement_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("last_statement_issue_date", models.DateField()),
                (
                    "plaid_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boltxplaid.plaidaccount",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.AlterField(
            model_name="apr",
            name="credit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="boltxplaid.creditliability",
            ),
        ),
        migrations.AlterField(
            model_name="propertyaddress",
            name="mortgage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="boltxplaid.mortgageliability",
            ),
        ),
        migrations.DeleteModel(
            name="Credit",
        ),
        migrations.DeleteModel(
            name="Mortgage",
        ),
    ]
