# Generated by Django 4.1.7 on 2023-04-25 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "boltxplaid",
            "0020_creditliability_mortgageliability_studentliability_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditliability",
            name="is_overdue",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="creditliability",
            name="last_payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="creditliability",
            name="last_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creditliability",
            name="last_statement_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="creditliability",
            name="minimum_payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="creditliability",
            name="next_payment_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creditliability",
            name="plaid_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boltxplaid.plaidaccount",
            ),
        ),
    ]
