# Generated by Django 4.1.7 on 2023-04-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0021_alter_creditliability_is_overdue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditliability",
            name="last_statement_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
