# Generated by Django 4.1.7 on 2023-04-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0022_alter_creditliability_last_statement_issue_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CreditLiability",
            new_name="CreditLine",
        ),
        migrations.RenameModel(
            old_name="MortgageLiability",
            new_name="MortgageLoan",
        ),
        migrations.RenameModel(
            old_name="StudentLiability",
            new_name="StudentLoan",
        ),
    ]
