# Generated by Django 4.1.7 on 2023-04-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0023_rename_creditliability_creditline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mortgageloan",
            name="account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="current_late_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="escrow_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="has_pmi",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="has_prepayment_penalty",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="interest_rate_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="interest_rate_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="last_payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="last_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="loan_term",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="maturity_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="next_monthly_payment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="next_payment_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="origination_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="origination_principal_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="past_due_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mortgageloan",
            name="plaid_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boltxplaid.plaidaccount",
            ),
        ),
    ]
