# Generated by Django 4.1.7 on 2023-04-25 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boltxplaid", "0024_alter_mortgageloan_account_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentloan",
            name="account_id",
        ),
        migrations.RemoveField(
            model_name="studentloan",
            name="disbursement_dates",
        ),
        migrations.AddField(
            model_name="studentloan",
            name="loan_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="loan_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="loan_status",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="loan_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="minimum_payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="next_payment_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="origination_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="origination_principal_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="outstanding_interest_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="payment_reference_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="pslf_status",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="repayment_plan",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="sequence_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="servicer_address",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="ytd_interest_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentloan",
            name="ytd_principal_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="apr",
            name="apr_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="apr",
            name="apr_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="apr",
            name="balance_subject_to_apr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="apr",
            name="credit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boltxplaid.creditline",
            ),
        ),
        migrations.AlterField(
            model_name="apr",
            name="interest_charge_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="propertyaddress",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="propertyaddress",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="propertyaddress",
            name="mortgage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boltxplaid.mortgageloan",
            ),
        ),
        migrations.AlterField(
            model_name="propertyaddress",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="propertyaddress",
            name="region",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="propertyaddress",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="studentloan",
            name="account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="studentloan",
            name="expected_payoff_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentloan",
            name="guarantor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="studentloan",
            name="interest_rate_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentloan",
            name="is_overdue",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="studentloan",
            name="last_payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentloan",
            name="last_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentloan",
            name="last_statement_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentloan",
            name="last_statement_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentloan",
            name="plaid_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boltxplaid.plaidaccount",
            ),
        ),
    ]
