# Generated by Django 4.1.7 on 2023-04-26 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boltxplaid", "0026_historicalstudentloan_historicalmortgageloan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "date",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="PlaidAccount",
            new_name="Account",
        ),
        migrations.RenameModel(
            old_name="HistoricalPlaidAccount",
            new_name="HistoricalAccount",
        ),
        migrations.RenameModel(
            old_name="PlaidItem",
            new_name="Item",
        ),
        migrations.RenameModel(
            old_name="PlaidTransaction",
            new_name="Transaction",
        ),
        migrations.AlterModelOptions(
            name="historicalaccount",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical account",
                "verbose_name_plural": "historical accounts",
            },
        ),
        migrations.DeleteModel(
            name="PlaidRequest",
        ),
    ]
